spring:
  application:
    name: users-api
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        page-parameter: page
        size-parameter: size

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,tracing
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
    display-operation-id: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: none
    show-extensions: true
    show-common-extensions: true
    deep-linking: true
    show-tags: true
    show-operations: true
    show-request-headers: true
    show-response-headers: true
    persist-authorization: true
    layout: StandaloneLayout
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - name: Users API
        url: /v3/api-docs
        display-name: Twitter Users API v1.0.0

# Настройки логирования
logging:
  level:
    com.twitter: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: WARN
    org.springframework.boot.context.embedded: WARN
    org.springframework.boot.actuate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${spring.application.name:} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${spring.application.name:} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
