global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: users-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'api:8081' ]

  - job_name: tweet-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'persons-api:8082' ]
  
  - job_name: follower-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'persons-api:8084' ]
        
  - job_name: admin-script-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'persons-api:8083' ]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: tempo
    metrics_path: /metrics
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: postgres
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
