version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: twitter-zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - twitter-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  twitter-network:
    driver: bridge

